# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dcdataset',
            fields=[
                ('dsid', models.IntegerField(db_column='dsid', primary_key=True, serialize=False)),
                ('dsname', models.CharField(db_column='dsname', max_length=45)),
                ('defineno', models.CharField(blank=True, db_column='defineno', max_length=45, null=True)),
                ('funcid', models.CharField(blank=True, db_column='funcid', max_length=45, null=True)),
                ('refreshint', models.CharField(blank=True, db_column='RereshInt', max_length=45, null=True)),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=45, null=True)),
            ],
            options={
                'db_table': 'SYSCFG_DCDATASET',
            },
        ),
        migrations.CreateModel(
            name='Dcitemdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, db_column='itemname', max_length=45, null=True)),
                ('datadate', models.CharField(db_column='datadate', max_length=20)),
                ('itemvalue1', models.FloatField(blank=True, db_column='itemvalue1', null=True)),
                ('itemvalue2', models.FloatField(blank=True, db_column='itemvalue2', null=True)),
                ('itemvalue3', models.FloatField(blank=True, db_column='itemvalue3', null=True)),
                ('itemvalue4', models.FloatField(blank=True, db_column='itemvalue4', null=True)),
                ('itemvalue5', models.FloatField(blank=True, db_column='itemvalue5', null=True)),
            ],
            options={
                'db_table': 'SYSCFG_DCITEMDATA',
            },
        ),
        migrations.CreateModel(
            name='Dcitemdefine',
            fields=[
                ('itemno', models.CharField(db_column='itemno', max_length=100, primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='itemname', max_length=100)),
                ('parentno', models.CharField(blank=True, db_column='parentno', max_length=100, null=True)),
                ('itemcode', models.CharField(blank=True, db_column='itemcode', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=45, null=True)),
            ],
            options={
                'db_table': 'SYSCFG_DCITEMDEFINE',
            },
        ),
        migrations.AddField(
            model_name='dcitemdata',
            name='itemno',
            field=models.ForeignKey(db_column='itemno', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Dcitemdefine'),
        ),
        migrations.AlterUniqueTogether(
            name='dcitemdata',
            unique_together=set([('itemno', 'datadate')]),
        ),
    ]
