# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsCal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Ops_cal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpsExamine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(blank=True, max_length=300, null=True)),
                ('avg_time', models.FloatField(blank=True, null=True)),
                ('process', models.FloatField(blank=True, null=True)),
                ('d_mamyi', models.FloatField(blank=True, null=True)),
                ('d_jixiao', models.FloatField(blank=True, null=True)),
                ('d_jifang', models.FloatField(blank=True, null=True)),
                ('d_peihe', models.FloatField(blank=True, null=True)),
                ('d_zhuanxiang', models.FloatField(blank=True, null=True)),
                ('d_jiajian', models.FloatField(blank=True, null=True)),
                ('d_sum', models.FloatField(blank=True, null=True)),
                ('d_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Ops_examine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpsJira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_type', models.CharField(blank=True, max_length=45, null=True)),
                ('sourcetype', models.CharField(blank=True, max_length=45, null=True)),
                ('sys_name', models.CharField(blank=True, max_length=45, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('d_date', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Ops_jira',
                'managed': False,
            },
        ),
    ]
